'@ssen/*':
  version: 1.0.0-alpha.3
  tag: latest
  module: commonjs
'@rocket-scripts/*':
  version: 1.0.0-alpha.3
  tag: latest
  module: commonjs
rocket-scripts:
  version: 1.0.0-alpha.3
  tag: latest
  module: commonjs
  packageJson:
    bin:
      'rocket-scripts': ./bin/rocket-scripts.js