'@ssen/*':
  version: 0.3.6-alpha.1
  tag: canary
  module: commonjs
'@rocket-scripts/*':
  version: 0.3.6-alpha.1
  tag: canary
  module: commonjs
rocket-scripts:
  version: 0.3.6-alpha.1
  tag: canary
  module: commonjs
  packageJson:
    bin:
      'rocket-scripts': ./bin/rocket-scripts.js