branches:
  only:
    - master
    - develop
language: node_js
node_js: '10'
cache: npm
git:
  submodules: false
before_install:
  - npm i -g npm@latest
  - git submodule sync && git submodule update --init
script:
  - npm run lint
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - npm run test:e2e:build
notifications:
  email:
    on_success: never
    on_failure: always