branches:
  only:
    - develop
language: node_js
node_js: '10'
cache: yarn
git:
  submodules: false
before_install:
  - sudo apt-get -y install tree
  - npm install -g yarn@latest
  - npm install -g verdaccio@latest # local npm registry for e2e test
  - git submodule sync && git submodule update --init # get fixtures
install:
  - yarn
script:
  - yarn lint
  - yarn coverage
#  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - yarn e2e
notifications:
  email:
    on_success: never
    on_failure: always