branches:
  only:
    - master
language: node_js
node_js: '10'
cache: yarn
git:
  submodules: false
before_install:
  - sudo apt-get -y install tree
  - npm install -g yarn@latest
  - git submodule sync && git submodule update --init # get fixtures
install:
  - yarn install
script:
  - yarn run lint
  - yarn run coverage
  - yarn run e2e
deploy:
  - provider: script
    script: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
    on:
      branch: master
notifications:
  email:
    on_success: never
    on_failure: always