'@ssen/collect-dependencies':
  version: 0.1.1
  tag: canary
'@ssen/promised':
  version: 0.1.1
  tag: canary
'@ssen/tmp-directory':
  version: 0.1.1
  tag: canary
'@ssen/tsconfig':
  version: 0.1.1
  tag: canary
'@ssen/flat-package-name':
  version: 0.1.1
  tag: canary
'@ssen/mirror-files':
  version: 0.1.1
  tag: canary
'@ssen/publish-packages':
  version: 0.1.1
  tag: canary
'@react-zeroconfig/core':
  version: 4.0.0-alpha.2
  tag: canary
'@react-zeroconfig/browserslist':
  version: 4.0.0-alpha.2
  tag: canary
'@react-zeroconfig/packages':
  version: 4.0.0-alpha.2
  tag: canary
'@react-zeroconfig/babel-preset':
  version: 3.28.0
  tag: latest
filesize-test:
  version: 0.1.4
  tag: latest
react-zeroconfig:
  version: 3.31.3
  tag: latest
