name: TEST

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.prettierrc.js'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.prettierrc.js'

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 15]
        os: [ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            node: 12
          - os: windows-latest
            node: 14

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Version
        run: |
          node --version
          yarn --version

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Lint
        run: yarn run lint

      - name: Coverage Test (Windows & macOS)
        if: matrix.os != 'ubuntu-latest'
        run: yarn run coverage

      - name: Coverage Test (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: "xvfb-run --auto-servernum --server-args='-screen 0, 1600x900x24' yarn run coverage"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./packages/coverage/coverage-final.json # ./{workspace}/coverage/coverage-final.json,./{workspace}/coverage/coverage-final.json...

      - name: Save Logs
        uses: actions/upload-artifact@v2
        with:
          name: logs-${{ matrix.os }}-node${{ matrix.node }}
          path: ${{ github.workspace }}/logs/*