name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Node Version
      run: node --version

    - name: NPM Version
      run: npm --version
    
    - name: Git submodule update
      run: git submodule sync && git submodule update --init # get fixtures

    - name: Install
      run: npm install

    - name: Build
      run: npm run build
    
    - name: Lint
      run: npm run lint
      
    - name: Coverage
      run: npm run coverage

    - name: E2E
      run: npm run e2e
